#!/bin/bash

# Compile Assignment 4
g++ -g -O0 -I. AssignmentFour/main.cpp AssignmentFour/source/Spice.cpp AssignmentFour/source/Knapsack.cpp AssignmentFour/source/Sorting.cpp AssignmentFour/source/SpiceHeist.cpp AssignmentFour/source/ParseHeistFile.cpp AssignmentFour/source/DirectedGraph.cpp AssignmentFour/source/DirectedGraphVertex.cpp AssignmentFour/source/DirectedGraphEdge.cpp AssignmentFour/source/BuildDirectedGraph.cpp AssignmentFour/source/Search.cpp AssignmentFour/source/PrintDirectedGraph.cpp -o program 

# Run the compiled executable
./program
