#!/bin/bash

# Compile the C++ source file
g++ -g -O0 main.cpp AssignmentOne/Node.cpp AssignmentOne/Queue.cpp AssignmentOne/Stack.cpp AssignmentOne/Sorting.cpp -o program
# Run the compiled executable
./program
