#!/bin/bash

# Compile the C++ source file for assignment 2
# g++ -g -O0 -I./AssignmentOne AssignmentThree/main.cpp AssignmentOne/Node.cpp AssignmentOne/Queue.cpp AssignmentOne/Stack.cpp AssignmentOne/Sorting.cpp AssignmentTwo/Search.cpp AssignmentTwo/HashTable.cpp AssignmentThree/BinarySearchTree.cpp AssignmentThree/BinarySearchTreeNode.cpp AssignmentThree/Graph.cpp AssignmentThree/GraphNode.cpp -o program 

# Compile Assignment 3
# g++ -g -O0 -I. AssignmentThree/main.cpp AssignmentThree/BinarySearchTree.cpp AssignmentThree/BinarySearchTreeNode.cpp AssignmentThree/Graph.cpp AssignmentThree/GraphNode.cpp -o program 

# Compile Assignment 4
g++ -g -O0 -I. AssignmentFour/main.cpp AssignmentFour/Spice.cpp AssignmentFour/Knapsack.cpp -o program 


# Run the compiled executable
./program
